# This is a basic workflow to help you get started with Actions

name: simple workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    name: the build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - run: echo hello > world.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: world.txt
          
  test:
    runs-on: ubuntu-latest
    name: running tests
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R

  security-scan:
    runs-on: windows-latest
    if: always()
    name: running sast
    needs: [ test ]
    steps:
      - uses: actions/checkout@v4
      - run: echo "hello!"
        shell: bash
